export const ProductHitGridViewStyles = {
  main: {
    '& a': {
      textDecoration: 'none',
      display: 'block',
      width: '100%',
      height: '478.64px',
      cursor: 'pointer',
    },
    cursor: 'pointer',
    width: '100%',
    maxWidth: { xs: '100%', sm: '332px' },
    height: '478.64px',
  },
  cardRoot: {
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    padding: 0,
    backgroundColor: '#FFFFFF',
    textDecoration: 'none',
    width: '100%',
    maxWidth: { xs: '100%', sm: '332px' },
    height: '478.64px',
    boxShadow: 'none',
    cursor: 'pointer',
    borderRadius: '14px',
    border: '1px solid #EAEAF1',
    boxSizing: 'border-box',
    overflow: 'hidden',
    transition: 'box-shadow 0.2s ease-in-out, border-color 0.2s ease-in-out',
    '&:hover': {
      boxShadow: '0 8px 24px rgba(27, 26, 36, 0.08)',
      borderColor: '#C9C7D6',
    },
    '&:hover .productNameStyle': {
      color: '#1B1A24',
    },
  },
  newTag: {
    width: 80,
    height: 41,
    top: '0px',
    position: 'absolute',
    left: '0px',
    zIndex: 2,
  },
  cardMedia: {
    width: '100%',
    position: 'relative',
    backgroundColor: '#F6F6FA',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
  },
  cardContent: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    padding: '15px',
    cursor: 'pointer',
  },
  brandLabel: {
    color: '#8B8AA0',
    fontSize: '10px',
    fontStyle: 'normal',
    fontWeight: '800',
    lineHeight: '16px',
    letterSpacing: '0.5px',
    textTransform: 'uppercase',
    fontFamily: 'Poppins',
    margin: 0,
  },
  productNameStyle: {
    color: '#1B1A24',
    fontSize: '13px',
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: '18.2px',
    letterSpacing: '0%',
    verticalAlign: 'middle',
    fontFamily: 'Poppins',
    display: '-webkit-box',
    WebkitLineClamp: 2,
    WebkitBoxOrient: 'vertical',
    overflow: 'hidden',
  },
  catalogNum: {
    color: '#8B8AA0',
    fontSize: '11px',
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: '18px',
    fontFamily: 'JetBrains Mono, monospace',
    marginTop: '4px',
  },
  tagsRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
    marginTop: '12px',
  },
  tagPill: {
    display: 'inline-flex',
    alignItems: 'center',
    backgroundColor: '#EDEDF4',
    borderRadius: '5px',
    padding: '4px 6px',
    color: '#1B1A24',
    fontSize: '9.5px',
    fontWeight: '700',
    lineHeight: '15px',
    fontFamily: 'Poppins',
  },
  badgeRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '12px',
    marginTop: '10px',
  },
  badgeItem: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  badgeText: {
    fontSize: '11px',
    fontWeight: '600',
    fontFamily: 'Poppins',
    lineHeight: '16px',
  },
  ctaButton: {
    marginTop: 'auto',
    paddingTop: '15px',
    '& .MuiButton-root': {
      width: '100%',
      backgroundColor: '#30299A',
      border: '1px solid #30299A',
      borderRadius: '9px',
      height: '36px',
      color: '#FFFFFF',
      fontFamily: 'Poppins',
      fontSize: '12px',
      fontWeight: '700',
      textTransform: 'none',
      boxShadow: 'none',
      '&:hover': {
        backgroundColor: '#231D77',
        borderColor: '#231D77',
        boxShadow: 'none',
      },
    },
  },
}
