export const buttonStyle = {
  featuredButtonContainer: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 'auto',
    position: 'relative',
    flexDirection: { md: 'row', sm: 'row', xs: 'column' },
    padding: '0 20px',
  },
  iconContainer: {
    display: 'flex',
    justifyContent: 'end',
    position: 'absolute',
    bottom: 0,
    right: 0,
  },
  featuredButtonContent: {
    width: '100%',
    height: '374px',
    position: 'relative',
    top: '180px',
    borderRadius: '26px 0px',
    zIndex: 1,
    backgroundColor: 'secondary.light',
    transform: 'translateY(-65%)',
    transition: 'transform 0.3s ease, box-shadow 0.3s ease, color 0.3s ease',
    border: '1px solid #E3E2FF',
    '&:hover': {
      boxShadow: '0px 8px 20px rgba(0, 0, 0, 0.2)',
    },
  },

  /* Primary Style */
  primaryImageContainer: {
    width: '100%',
    height: '255px',
    borderRadius: '5px',
    position: 'relative',
    overflow: 'hidden',
    zIndex: 2,
    transition: 'box-shadow 0.3s ease',
    boxShadow: 'none',
  },
  primaryHeadingText: {
    width: '347px',
    height: 'auto',
    color: 'primary.main',
    fontSize: '20px',
    fontWeight: '500',
    lineHeight: '25px',
    fontFamily: 'Poppins',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: '95px',
    paddingRight: '20px',
    paddingLeft: '20px',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: 'primary.light',
    },
  },
  primaryParagraphText: {
    width: '347px',
    height: 'auto',
    color: 'primary.main',
    fontSize: '16px',
    fontWeight: '300',
    lineHeight: '25px',
    fontFamily: 'Poppins',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: '24px',
    paddingRight: '20px',
    paddingLeft: '20px',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: 'primary.light',
    },
  },
  arrowPrimaryButton: {
    width: '61px',
    height: '74px',
    color: 'primary.main',
    borderRadius: '26px 0px',
    border: '1px solid  primary.main',
    backgroundColor: 'primary.main',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: 'primary.light',
    },
  },
  primaryArrowIcon: {
    color: 'secondary.light',
  },

  /* Secondary Style */
  secondaryImageContainer: {
    width: '100%',
    height: '255px',
    borderRadius: '5px',
    position: 'relative',
    overflow: 'hidden',
    zIndex: 2,
    transition: 'box-shadow 0.3s ease',
    boxShadow: 'none',
  },
  secondaryHeadingText: {
    width: '347px',
    height: 'auto',
    color: 'primary.main',
    fontSize: '20px',
    fontWeight: '500',
    lineHeight: '25px',
    fontFamily: 'Poppins',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: '95px',
    paddingRight: '20px',
    paddingLeft: '20px',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: 'primary.light',
    },
  },
  secondaryParagraphText: {
    width: '347px',
    height: 'auto',
    color: 'primary.main',
    fontSize: '16px',
    fontWeight: '300',
    lineHeight: '25px',
    fontFamily: 'Poppins',
    display: 'flex',
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: '24px',
    paddingRight: '20px',
    paddingLeft: '20px',
    transition: 'color 0.3s ease',
    '&:hover': {
      color: 'primary.light',
    },
  },
  arrowSecondaryButton: {
    width: '61px',
    height: '74px',
    color: 'secondary.main',
    borderRadius: '26px 0px',
    backgroundColor: 'secondary.main',
    transition: 'background-color 0.3s ease',
    '&:hover': {
      backgroundColor: 'primary.light',
    },
  },
  secondaryArrowIcon: {
    color: 'primary.main',
  },
}
