export const LeftTextHeroStyle = {
  leftTxtHeroContainer: {
    display: 'flex',
    justifyContent: 'end',
    alignItems: 'center',
    textAlign: 'center',
    width: '100%',
    maxWidth: '1366px',
    height: { md: '551px', sm: '550px', xs: '596px' },
    position: 'relative',
    flexDirection: { md: 'row', sm: 'row', xs: 'column' },
    paddingTop: '27px',
  },
  leftTxtBox: {
    width: '80%',
    minHeight: { md: '508px' },
    position: 'absolute',
    top: '48%',
    transform: 'translateY(-50%)',
    left: 0,
    zIndex: 1,
    borderRadius: '5px',
    background: '#EDEDED',
    textAlign: 'left',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    flexDirection: 'column',
    padding: '0 45px',
    backgroundSize: { md: 'cover', sm: 'contain', xs: 'cover' },
    backgroundRepeat: 'no-repeat',
    backgroundPosition: { xs: 'right top' },
    '@media (max-width: 600px)': {
      width: '100%',
      height: 'auto',
      position: 'absolute',
      top: '30%',
      padding: '20px',
      zIndex: 1,
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
    },
    '@media (min-width: 601px) and (max-width: 990px)': {
      padding: '0 20px',
      zIndex: 1,
      height: 'auto',
    },
  },
  leftTxtHeading: {
    color: 'primary.main',
    width: { md: '589px', sm: '400px', xs: '100%' },
    height: { md: 'auto', xs: 'auto' },
    fontFamily: 'Poppins',
    fontSize: { md: '40px', sm: '30px', xs: '30px' },
    fontWeight: { md: 500, xs: 500 },
    lineHeight: { md: '55px', sm: '40px', xs: '42px' },
    marginBottom: { md: '27px', xs: '10px' },
    padding: { sm: '0 10px' },
    '@media (min-width: 900px) and (max-width: 990px)': {
      width: '560px',
    },
    '@media (min-width: 991px) and (max-width: 1023px)': {
      width: '540px',
    },
  },
  leftTxtParagraph: {
    color: '#020027',
    width: { md: '589px', sm: '350px', xs: '100%' },
    height: 'auto',
    fontFamily: 'Poppins',
    fontSize: { md: '22px', sm: '16px', xs: '18px' },
    fontWeight: { md: 300, xs: 300 },
    lineHeight: { md: '35px', sm: '30px', xs: '28px' },
    marginBottom: { md: '27px', xs: '15px' },
    padding: { sm: '0 10px' },
    '@media (min-width: 900px) and (max-width: 990px)': {
      width: '523px',
    },
    '@media (min-width: 991px) and (max-width: 1023px)': {
      width: '523px',
    },
  },
  leftTxtPrimaryButton: {
    backgroundColor: 'primary.main',
    color: 'secondary.light',
    borderRadius: '0px 26px',
    border: '1px solid secondary.light',
    display: 'inline-flex',
    padding: '12px 18px',
    justifyContent: 'center',
    alignItems: 'center',
    width: 'auto',
    height: { md: '49px' },
    fontSize: '16px',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: 'primary.light',
    },
  },
  leftTxtSecondaryButton: {
    backgroundColor: 'secondary.light',
    color: 'primary.main',
    borderRadius: '0px 26px',
    border: '1px solid primary.main',
    display: 'inline-flex',
    padding: '12px 18px',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '10px',
    width: 'auto',
    height: { md: '49px' },
    fontSize: '16px',
    fontWeight: 500,
    '&:hover': {
      backgroundColor: 'secondary.main',
      border: '1px solid secondary.main',
      color: 'primary.light',
    },
  },
  leftTxtImage: {
    height: { md: '551px', sm: 'auto', xs: 'auto' },
    minHeight: { xs: '285px' },
    width: { md: '48%', sm: '48%', xs: '100%' },
    position: 'relative',
    zIndex: '2',
    top: '10%',
    '@media (max-width: 600px)': {
      top: '1%',
      '@media (min-width: 406px) and (max-width: 419px)': {
        top: '2%',
      },
      '@media (min-width: 420px) and (max-width: 427px)': {
        top: '3%',
      },
      '@media (min-width: 437px) and (max-width: 450px)': {
        top: '2%',
      },
      '@media (min-width: 451px) and (max-width: 460px)': {
        top: '3%',
      },
      '@media (min-width: 461px) and (max-width: 477px)': {
        top: '5%',
      },
      '@media (min-width: 478px) and (max-width: 490px)': {
        top: '7%',
      },
      '@media (min-width: 491px) and (max-width: 520px)': {
        top: '8%',
      },
      '@media (min-width: 521px) and (max-width: 530px)': {
        top: '9%',
      },
      '@media (min-width: 531px) and (max-width: 540px)': {
        top: '10%',
      },
      '@media (min-width: 541px) and (max-width: 560px)': {
        top: '13%',
      },
      '@media (min-width: 561px) and (max-width: 600px)': {
        top: '15%',
      },
    },
    '@media (min-width: 601px) and (max-width: 990px)': {
      width: '48%',
    },
  },
}
