name: Commitlint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  lint:
    name: Validate Pull Request Name (conventional-commit)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install commitlint and the conventional config
      - name: Install Commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional

      # Run commitlint on the pull request title using npx
      - name: Validate PR Title
        run: npx commitlint --config ./commitlint.config.js
# name: Commitlint
# on:
#   pull_request:
#     types: ['opened', 'edited', 'reopened', 'synchronize']

# jobs:
#   lint:
#     name: Validate Pull Request Name (conventional-commit)
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Install Dependencies
#         run: npm install @commitlint/config-conventional
#       - uses: JulienKode/pull-request-name-linter-action@v0.1.2
